server:
  port: 2004

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///Users/three/workspaces/my-projs/ant-network
#          basedir: target/config
          search-paths: config-repo
          repos:
            local:
                pattern: local*
                uri: file:///Users/three/workspaces/my-projs/ant-network
                search-paths: config-repo
        encrypt:
          enabled: false

---
spring:
  profiles: cloud
eureka:
  password: password
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/
